apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kriten.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kriten.selectorLabels" . | nindent 6 }}
      app: {{ include "kriten.fullname" . }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "kriten.selectorLabels" . | nindent 8 }}
        app: {{ include "kriten.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kriten.serviceAccountName" . }}
      containers:
      - name: {{ include "kriten.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 8080
        env:
          - name: "ENV"
            value: "production"
          - name: "ROOT_SECRET"
            value: {{ include "kriten.fullname" . }}-root
        envFrom:
          - secretRef:
              name: {{ include "kriten.fullname" . }}-env
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
