{{- if .Values.frontend.enabled }}
{{ $frontendName := printf "%s-%s" (include "kriten.fullname" .) "frontend" -}}
{{- $svcPort := .Values.frontend.service.port -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $frontendName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "kriten.selectorLabels" . | nindent 6 }}
      app: {{ $frontendName }}
  template:
    metadata:
      labels:
        {{- include "kriten.selectorLabels" . | nindent 8 }}
        app: {{ $frontendName }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $frontendName }}
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
          - containerPort: 80
        env:
          - name: BACKEND
            value: "http://{{ .Values.frontend.backendAddress }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $frontendName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kriten.selectorLabels" . | nindent 8 }}
spec:
  selector:
    {{- include "kriten.selectorLabels" . | nindent 4 }}
    app: {{ $frontendName }}
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ $svcPort }}
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $frontendName }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.frontend.ingress.className }}
  rules:
    {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $frontendName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}

