apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kriten.fullname" . }}-root
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: "root"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "kriten.fullname" . }}-env
type: Opaque
stringData:
  NAMESPACE : "{{ .Values.namespace }}"
  JOBS_TTL : "{{ .Values.jobsTTL }}"
{{- if .Values.ldap.enabled }}
  LDAP_BIND_USER: "{{ .Values.ldap.bindUser }}"
  LDAP_BIND_PASS: "{{ .Values.ldap.bindPass }}"
  LDAP_FQDN     : "{{ .Values.ldap.fqdn }}"
  LDAP_PORT     : "{{ .Values.ldap.port }}"
  LDAP_BASE_DN  : "{{ .Values.ldap.baseDN }}"
{{- end }}
  JWT_KEY: "{{ .Values.jwt.key }}"
  JWT_EXPIRY_SECONDS: "{{ .Values.jwt.expiry_seconds }}"
  DB_NAME : "{{ .Values.postgresql.auth.database }}"
  DB_HOST : "{{ include "kriten.fullname" . }}-postgresql"
  DB_USER : "{{ .Values.postgresql.auth.username }}"
  DB_PASSWORD : "{{ .Values.postgresql.auth.password }}"
  DB_SSL : "disable"
{{- if .Values.elasticSearch.enabled }}
  ES_CLOUD_ID: "{{ .Values.elasticSearch.cloudID }}"
  ES_API_KEY : "{{ .Values.elasticSearch.apiKey }}"
  ES_INDEX   : "{{ .Values.elasticSearch.index }}"
{{- end }}

