{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kriten.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kriten.selectorLabels" . | nindent 8 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 namespace: {{ .Release.Namespace }}
 name: {{ include "kriten.fullname" . }}-role
rules:
- apiGroups:
    - ""
    - "apps"
    - "batch"
  resources:
    - "secrets"
    - "configmaps"
    - "jobs"
    - "pods"
    - "pods/log"
  verbs:
    - "get"
    - "list"
    - "watch"
    - "create"
    - "update"
    - "patch"
    - "delete"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: {{ include "kriten.fullname" . }}-rb
 namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "kriten.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
 kind: Role
 name: {{ include "kriten.fullname" . }}-role
 apiGroup: rbac.authorization.k8s.io
 {{- end }}
